# ... existing code ...
# Install dependencies
echo -e "${BLUE}Installing dependencies...${NC}"
pip install -r requirements-dev.txt
echo -e "${GREEN}Dependencies installed.${NC}"
# ... existing code ... 