name: course-recommender-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
    - azureml-defaults
    - pandas
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - numpy
    - joblib