[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[logger]
level = "info"

[runner]
magicEnabled = true
fastReruns = true

[browser]
gatherUsageStats = false 