name: LearnMate CI/CD

on:
  push:
    branches:
      - '*'  # Run tests on any push
  pull_request:
    branches:
      - main  # Run tests and deploy on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/test_recommender.py || true  # Warns but doesn’t fail
        
  deploy:
    # The model will only be deployed if tests pass and the PR is merged
    needs: test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: LearnMate
          slot-name: production