name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create necessary directories
        run: |
          mkdir -p backend/data/chat_requests
          mkdir -p backend/data/metrics
          mkdir -p backend/data/processed/metadata
          
      - name: Set STREAMLIT_SHARING environment variable
        run: echo "STREAMLIT_SHARING=1" >> $GITHUB_ENV
        
      # This step isn't needed for Streamlit Cloud, as the deployment is 
      # handled by Streamlit Cloud service itself. This workflow mainly
      # ensures the repository is ready for deployment.
        
      - name: Deployment Info
        run: |
          echo "✅ Repository is ready for Streamlit Cloud deployment"
          echo "To deploy to Streamlit Cloud:"
          echo "1. Go to https://share.streamlit.io/"
          echo "2. Connect your repository"
          echo "3. Set the main file path to 'streamlit_eda.py'" 