name: LearnMate Test on Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - deployment-vercel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Download NLTK data
          python -c "import nltk; nltk.download('stopwords'); nltk.download('wordnet')"
      - name: Set Python path
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Set Azure ML environment variables
        run: |
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "AZURE_RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}" >> $GITHUB_ENV
          echo "AZURE_WORKSPACE_NAME=${{ secrets.AZURE_WORKSPACE_NAME }}" >> $GITHUB_ENV
      - name: Run tests
        run: pytest tests/test_recommender.py -v --capture=no